import { Item } from '../types/models/item.model'
// Tipos:
// Armadura [1, 10, 11, 4, 40, 41]
// Robe [2, 20, 21, 3, 30, 31]
//All Class [0]
// Armas
// Calça / Calça Leve
// Bota de Combate / Sapato
// Colar
// Brinco
// Anel

export const items: Item[] = [
    {
        id: 1,
        imageSource: '',
        name: 'Camiseta de Algodao',
        type: 'Armadura',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: true, 
        minLevel: 1,

    },
    {
        id: 2,
        imageSource: '',
        name: 'Jaqueta de Couro',
        type: 'Armadura',
        class: [0],
        power: 5,
        armor: 4,
        primaryAttr: 1,
        buyPrice: 2,
        sellPrice: 1,
        buyable: true, 
        minLevel: 1,

    },
    {
        id: 3,
        imageSource: '',
        name: 'Armadura de Couro',
        type: 'Armadura',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 4,
        imageSource: '',
        name: 'Armadura de Osso',
        type: 'Armadura',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 5,
        imageSource: '',
        name: 'Vestimenta de Couro',
        type: 'Armadura',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 6,
        imageSource: '',
        name: 'Cota de Malha',
        type: 'Armadura',
        class: [0],
        power: 14,
        armor: 10,
        primaryAttr: 4,
        buyPrice: 10,
        sellPrice: 5,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 7,
        imageSource: '',
        name: 'Armadura de Escamas',
        type: 'Armadura',
        class: [],
        power: 16,
        armor: 10,
        primaryAttr: 6,
        buyPrice: 15,
        sellPrice: 7,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 8,
        imageSource: '',
        name: 'Armadura de Latão',
        type: 'Armadura',
        class: [0],
        power: 18,
        armor: 13,
        primaryAttr: 5,
        buyPrice: 20,
        sellPrice: 10,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 9,
        imageSource: '',
        name: 'Armadura de Bronze',
        type: 'Armadura',
        class: [0],
        power: 24,
        armor: 20,
        primaryAttr: 4,
        buyPrice: 30,
        sellPrice: 15,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 10,
        imageSource: '',
        name: 'Armadura de Aço',
        type: 'Armadura',
        class: [0],
        power: 31,
        armor: 25,
        primaryAttr: 6,
        buyPrice: 50,
        sellPrice: 25,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 11,
        imageSource: '',
        name: 'Armadura de Placas',
        type: 'Armadura',
        class: [0],
        power: 40,
        armor: 31,
        primaryAttr: 9,
        buyPrice: 80,
        sellPrice: 40,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 100,
        imageSource: '',
        name: 'Calça de Algodao',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 101,
        imageSource: '',
        name: 'Calça de Couro',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 102,
        imageSource: '',
        name: 'Grevas de Couro',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 103,
        imageSource: '',
        name: 'Grevas de Osso',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 104,
        imageSource: '',
        name: 'Saia Romana de Couro',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 105,
        imageSource: '',
        name: 'Calça de Malha',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 106,
        imageSource: '',
        name: 'Calça de Escamas',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 107,
        imageSource: '',
        name: 'Calça de Latão',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 108,
        imageSource: '',
        name: 'Calça de Bronze',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 109,
        imageSource: '',
        name: 'Calça de Aço',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 110,
        imageSource: '',
        name: 'Calça de Placas',
        type: 'Calça',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 200,
        imageSource: '',
        name: 'Luvas de Algodao',
        type: 'Luva',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 201,
        imageSource: '',
        name: 'Bracelete de Couro',
        type: 'Luva',
        class: [0],
        power: 5,
        armor: 4,
        primaryAttr: 1,
        buyPrice: 2,
        sellPrice: 1,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 202,
        imageSource: '',
        name: 'Manopla de Couro',
        type: 'Luva',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 203,
        imageSource: '',
        name: 'Manopla de Osso',
        type: 'Luva',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 204,
        imageSource: '',
        name: 'Luvas de Couro',
        type: 'Luva',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 205,
        imageSource: '',
        name: 'Luvas de Malha',
        type: 'Luva',
        class: [0],
        power: 14,
        armor: 10,
        primaryAttr: 4,
        buyPrice: 10,
        sellPrice: 5,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 206,
        imageSource: '',
        name: 'Manopla de Escamas',
        type: 'Luva',
        class: [],
        power: 16,
        armor: 10,
        primaryAttr: 6,
        buyPrice: 15,
        sellPrice: 7,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 207,
        imageSource: '',
        name: 'Manopla de Latão',
        type: 'Luva',
        class: [0],
        power: 18,
        armor: 13,
        primaryAttr: 5,
        buyPrice: 20,
        sellPrice: 10,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 208,
        imageSource: '',
        name: 'Manopla de Bronze',
        type: 'Luva',
        class: [0],
        power: 24,
        armor: 20,
        primaryAttr: 4,
        buyPrice: 30,
        sellPrice: 15,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 209,
        imageSource: '',
        name: 'Manopla de Aço',
        type: 'Luva',
        class: [0],
        power: 31,
        armor: 25,
        primaryAttr: 6,
        buyPrice: 50,
        sellPrice: 25,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 210,
        imageSource: '',
        name: 'Manopla de Placas',
        type: 'Luva',
        class: [0],
        power: 40,
        armor: 31,
        primaryAttr: 9,
        buyPrice: 80,
        sellPrice: 40,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 300,
        imageSource: '',
        name: 'Luvas de Algodao',
        type: 'Luva',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 301,
        imageSource: '',
        name: 'Bracelete de Couro',
        type: 'Luva',
        class: [0],
        power: 5,
        armor: 4,
        primaryAttr: 1,
        buyPrice: 2,
        sellPrice: 1,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 302,
        imageSource: '',
        name: 'Manopla de Couro',
        type: 'Luva',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 303,
        imageSource: '',
        name: 'Manopla de Osso',
        type: 'Luva',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 304,
        imageSource: '',
        name: 'Luvas de Couro',
        type: 'Luva',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 305,
        imageSource: '',
        name: 'Luvas de Malha',
        type: 'Luva',
        class: [0],
        power: 14,
        armor: 10,
        primaryAttr: 4,
        buyPrice: 10,
        sellPrice: 5,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 306,
        imageSource: '',
        name: 'Manopla de Escamas',
        type: 'Luva',
        class: [],
        power: 16,
        armor: 10,
        primaryAttr: 6,
        buyPrice: 15,
        sellPrice: 7,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 307,
        imageSource: '',
        name: 'Manopla de Latão',
        type: 'Luva',
        class: [0],
        power: 18,
        armor: 13,
        primaryAttr: 5,
        buyPrice: 20,
        sellPrice: 10,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 308,
        imageSource: '',
        name: 'Manopla de Bronze',
        type: 'Luva',
        class: [0],
        power: 24,
        armor: 20,
        primaryAttr: 4,
        buyPrice: 30,
        sellPrice: 15,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 309,
        imageSource: '',
        name: 'Manopla de Aço',
        type: 'Luva',
        class: [0],
        power: 31,
        armor: 25,
        primaryAttr: 6,
        buyPrice: 50,
        sellPrice: 25,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 310,
        imageSource: '',
        name: 'Manopla de Placas',
        type: 'Luva',
        class: [0],
        power: 40,
        armor: 31,
        primaryAttr: 9,
        buyPrice: 80,
        sellPrice: 40,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 400,
        imageSource: '',
        name: 'Capuz de Algodao',
        type: 'Capacete',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false,
         minLevel: 1,
    },
    {
        id: 401,
        imageSource: '',
        name: 'Elmo de Couro',
        type: 'Capacete',
        class: [0],
        power: 5,
        armor: 4,
        primaryAttr: 1,
        buyPrice: 2,
        sellPrice: 1,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 402,
        imageSource: '',
        name: 'Capuz de Couro',
        type: 'Capacete',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 403,
        imageSource: '',
        name: 'Elmo de Osso',
        type: 'Capacete',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 404,
        imageSource: '',
        name: 'Capuz de Couro',
        type: 'Capacete',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 405,
        imageSource: '',
        name: 'Capuz de Malha',
        type: 'Capacete',
        class: [0],
        power: 14,
        armor: 10,
        primaryAttr: 4,
        buyPrice: 10,
        sellPrice: 5,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 406,
        imageSource: '',
        name: 'Elmo de Escamas',
        type: 'Capacete',
        class: [],
        power: 16,
        armor: 10,
        primaryAttr: 6,
        buyPrice: 15,
        sellPrice: 7,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 407,
        imageSource: '',
        name: 'Elmo de Latão',
        type: 'Capacete',
        class: [0],
        power: 18,
        armor: 13,
        primaryAttr: 5,
        buyPrice: 20,
        sellPrice: 10,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 408,
        imageSource: '',
        name: 'Elmo de Bronze',
        type: 'Capacete',
        class: [0],
        power: 24,
        armor: 20,
        primaryAttr: 4,
        buyPrice: 30,
        sellPrice: 15,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 409,
        imageSource: '',
        name: 'Elmo de Aço',
        type: 'Capacete',
        class: [0],
        power: 31,
        armor: 25,
        primaryAttr: 6,
        buyPrice: 50,
        sellPrice: 25,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 410,
        imageSource: '',
        name: 'Elmo de Placas',
        type: 'Capacete',
        class: [0],
        power: 40,
        armor: 31,
        primaryAttr: 9,
        buyPrice: 80,
        sellPrice: 40,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 1000,
        imageSource: '',
        name: 'Staff de Madeira',
        type: 'Arma',
        class: [0],
        power: 2,
        armor: 2,
        primaryAttr: 0,
        buyPrice: 0,
        sellPrice: 0,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 1001,
        imageSource: '',
        name: 'Rod de Madeira',
        type: 'Arma',
        class: [0],
        power: 5,
        armor: 4,
        primaryAttr: 1,
        buyPrice: 2,
        sellPrice: 1,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 1002,
        imageSource: '',
        name: 'Greatsword de Madeira',
        type: 'Arma',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 1003,
        imageSource: '',
        name: 'Sword de Madeira',
        type: 'Arma',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 1004,
        imageSource: '',
        name: 'Bow de Madeira',
        type: 'Arma',
        class: [0],
        power: 9,
        armor: 7,
        primaryAttr: 2,
        buyPrice: 4,
        sellPrice: 2,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 1005,
        imageSource: '',
        name: 'Shield de Madeira',
        type: 'Arma',
        class: [0],
        power: 14,
        armor: 10,
        primaryAttr: 4,
        buyPrice: 10,
        sellPrice: 5,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 1006,
        imageSource: '',
        name: 'Dagger de Madeira',
        type: 'Arma',
        class: [],
        power: 16,
        armor: 10,
        primaryAttr: 6,
        buyPrice: 15,
        sellPrice: 7,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 1007,
        imageSource: '',
        name: 'Staff de Aço',
        type: 'Arma',
        class: [0],
        power: 18,
        armor: 13,
        primaryAttr: 5,
        buyPrice: 20,
        sellPrice: 10,
        buyable: false, 
        minLevel: 1,
    },
    {
        id: 1008,
        imageSource: '',
        name: 'Rod de Aço',
        type: 'Arma',
        class: [0],
        power: 24,
        armor: 20,
        primaryAttr: 4,
        buyPrice: 30,
        sellPrice: 15,
        buyable: false, 
        minLevel: 1,

    },
    {
        id: 1009,
        imageSource: '',
        name: 'Greatsword de Aço',
        type: 'Arma',
        class: [0],
        power: 31,
        armor: 25,
        primaryAttr: 6,
        buyPrice: 50,
        sellPrice: 25,
        buyable: false,
        minLevel: 1,
    },
    {
        id: 1010,
        imageSource: '',
        name: 'Sword de Aço',
        type: 'Arma',
        class: [0],
        power: 40,
        armor: 31,
        primaryAttr: 9,
        buyPrice: 80,
        sellPrice: 40,
        buyable: false,
        minLevel: 1,
    },
    {
        id: 1011,
        imageSource: '',
        name: 'Shield de Aço',
        type: 'Arma',
        class: [0],
        power: 40,
        armor: 31,
        primaryAttr: 9,
        buyPrice: 80,
        sellPrice: 40,
        buyable: false,
        minLevel: 1,
    },
    {
        id: 1012,
        imageSource: '',
        name: 'Bow de Aço',
        type: 'Arma',
        class: [0],
        power: 40,
        armor: 31,
        primaryAttr: 9,
        buyPrice: 80,
        sellPrice: 40,
        buyable: false,
        minLevel: 1,
    },
    {
        id: 1013,
        imageSource: '',
        name: 'Dagger de Aço',
        type: 'Arma',
        class: [0],
        power: 40,
        armor: 31,
        primaryAttr: 9,
        buyPrice: 80,
        sellPrice: 40,
        buyable: false,
        minLevel: 1,
    },
]